-- MySQL Script generated by MySQL Workbench
-- 11/23/17 14:36:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BeaconsProj
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BeaconsProj` ;

-- -----------------------------------------------------
-- Schema BeaconsProj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BeaconsProj` DEFAULT CHARACTER SET utf8 ;
USE `BeaconsProj` ;

-- -----------------------------------------------------
-- Table `BeaconsProj`.`Beacon1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeaconsProj`.`Beacon1` ;

CREATE TABLE IF NOT EXISTS `BeaconsProj`.`Beacon1` (
  `idBeacon1` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeaconsProj`.`Beacon2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeaconsProj`.`Beacon2` ;

CREATE TABLE IF NOT EXISTS `BeaconsProj`.`Beacon2` (
  `idBeacon2` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeaconsProj`.`Beacon3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeaconsProj`.`Beacon3` ;

CREATE TABLE IF NOT EXISTS `BeaconsProj`.`Beacon3` (
  `idBeacon3` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeaconsProj`.`Beacon4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeaconsProj`.`Beacon4` ;

CREATE TABLE IF NOT EXISTS `BeaconsProj`.`Beacon4` (
  `idBeacon4` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon4`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeaconsProj`.`Statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeaconsProj`.`Statistics` ;

CREATE TABLE IF NOT EXISTS `BeaconsProj`.`Statistics` (
  `idStatistics` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  `Beacon1_idBeacon1` INT NOT NULL,
  `Beacon3_idBeacon3` INT NOT NULL,
  `Beacon2_idBeacon2` INT NOT NULL,
  `Beacon4_idBeacon4` INT NOT NULL,
  PRIMARY KEY (`idStatistics`),
  INDEX `fk_Statistics_Beacon1_idx` (`Beacon1_idBeacon1` ASC),
  INDEX `fk_Statistics_Beacon31_idx` (`Beacon3_idBeacon3` ASC),
  INDEX `fk_Statistics_Beacon21_idx` (`Beacon2_idBeacon2` ASC),
  INDEX `fk_Statistics_Beacon41_idx` (`Beacon4_idBeacon4` ASC),
  CONSTRAINT `fk_Statistics_Beacon1`
    FOREIGN KEY (`Beacon1_idBeacon1`)
    REFERENCES `BeaconsProj`.`Beacon1` (`idBeacon1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Beacon31`
    FOREIGN KEY (`Beacon3_idBeacon3`)
    REFERENCES `BeaconsProj`.`Beacon3` (`idBeacon3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Beacon21`
    FOREIGN KEY (`Beacon2_idBeacon2`)
    REFERENCES `BeaconsProj`.`Beacon2` (`idBeacon2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Beacon41`
    FOREIGN KEY (`Beacon4_idBeacon4`)
    REFERENCES `BeaconsProj`.`Beacon4` (`idBeacon4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeaconsProj`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeaconsProj`.`Users` ;

CREATE TABLE IF NOT EXISTS `BeaconsProj`.`Users` (
  `idUsers` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BeaconsProj`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `BeaconsProj`;
INSERT INTO `BeaconsProj`.`Users` (`idUsers`, `Name`, `Password`) VALUES (1, 'Thomas', 'Azerty123');

COMMIT;

