-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 18:13:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql11205324` DEFAULT CHARACTER SET utf8 ;
USE `sql11205324` ;

-- -----------------------------------------------------
-- Table `mydb`.`Beacon1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql11205324`.`Beacon1` ;

CREATE TABLE IF NOT EXISTS `sql11205324`.`Beacon1` (
  `idBeacon1` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beacon2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql11205324`.`Beacon2` ;

CREATE TABLE IF NOT EXISTS `sql11205324`.`Beacon2` (
  `idBeacon2` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beacon3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql11205324`.`Beacon3` ;

CREATE TABLE IF NOT EXISTS `sql11205324`.`Beacon3` (
  `idBeacon3` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beacon4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql11205324`.`Beacon4` ;

CREATE TABLE IF NOT EXISTS `sql11205324`.`Beacon4` (
  `idBeacon4` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Distance` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`idBeacon4`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql11205324`.`Statistics` ;

CREATE TABLE IF NOT EXISTS `sql11205324`.`Statistics` (
  `idStatistics` INT NOT NULL,
  `Device` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  `Beacon1_idBeacon1` INT NOT NULL,
  `Beacon3_idBeacon3` INT NOT NULL,
  `Beacon2_idBeacon2` INT NOT NULL,
  `Beacon4_idBeacon4` INT NOT NULL,
  PRIMARY KEY (`idStatistics`),
  INDEX `fk_Statistics_Beacon1_idx` (`Beacon1_idBeacon1` ASC),
  INDEX `fk_Statistics_Beacon31_idx` (`Beacon3_idBeacon3` ASC),
  INDEX `fk_Statistics_Beacon21_idx` (`Beacon2_idBeacon2` ASC),
  INDEX `fk_Statistics_Beacon41_idx` (`Beacon4_idBeacon4` ASC),
  CONSTRAINT `fk_Statistics_Beacon1`
    FOREIGN KEY (`Beacon1_idBeacon1`)
    REFERENCES `sql11205324`.`Beacon1` (`idBeacon1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Beacon31`
    FOREIGN KEY (`Beacon3_idBeacon3`)
    REFERENCES `sql11205324`.`Beacon3` (`idBeacon3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Beacon21`
    FOREIGN KEY (`Beacon2_idBeacon2`)
    REFERENCES `sql11205324`.`Beacon2` (`idBeacon2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statistics_Beacon41`
    FOREIGN KEY (`Beacon4_idBeacon4`)
    REFERENCES `sql11205324`.`Beacon4` (`idBeacon4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
