-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 14:44:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ErasmusProject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ErasmusProject` ;

-- -----------------------------------------------------
-- Schema ErasmusProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ErasmusProject` DEFAULT CHARACTER SET utf8 ;
USE `ErasmusProject` ;

-- -----------------------------------------------------
-- Table `ErasmusProject`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErasmusProject`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `ErasmusProject`.`Rooms` (
  `idRoom` INT(11) NOT NULL AUTO_INCREMENT,
  `nameRoom` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ErasmusProject`.`Devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErasmusProject`.`Devices` ;

CREATE TABLE IF NOT EXISTS `ErasmusProject`.`Devices` (
  `idDevice` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `Rooms_idRoom` INT(11) NOT NULL,
  PRIMARY KEY (`idDevice`),
  INDEX `fk_Devices_Rooms_idx` (`Rooms_idRoom` ASC),
  CONSTRAINT `fk_Devices_Rooms`
    FOREIGN KEY (`Rooms_idRoom`)
    REFERENCES `ErasmusProject`.`Rooms` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ErasmusProject`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErasmusProject`.`Users` ;

CREATE TABLE IF NOT EXISTS `ErasmusProject`.`Users` (
  `idUsers` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ErasmusProject`.`Values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ErasmusProject`.`Values` ;

CREATE TABLE IF NOT EXISTS `ErasmusProject`.`Values` (
  `idValues` INT NOT NULL AUTO_INCREMENT,
  `Rooms_idRoom` INT(11) NOT NULL,
  `valueBeacon1` VARCHAR(45) NULL,
  `valueBeacon2` VARCHAR(45) NULL,
  `valueBeacon3` VARCHAR(45) NULL,
  `valueBeacon4` VARCHAR(45) NULL,
  PRIMARY KEY (`idValues`),
  INDEX `fk_Values_Rooms1_idx` (`Rooms_idRoom` ASC),
  CONSTRAINT `fk_Values_Rooms1`
    FOREIGN KEY (`Rooms_idRoom`)
    REFERENCES `ErasmusProject`.`Rooms` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ErasmusProject`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `ErasmusProject`;
INSERT INTO `ErasmusProject`.`Users` (`idUsers`, `name`, `password`) VALUES (1, 'thomas', 'Azerty123');
INSERT INTO `ErasmusProject`.`Users` (`idUsers`, `name`, `password`) VALUES (2, 'wouter', 'Azerty123');

COMMIT;

